import { portableIntegration, portableCatalog } from "./portable";
import { discoverRecipes } from "./discovery";
import { z } from "zod";
import { RESOURCES } from "../core/resources";
import { FLUTE_BRAND } from "../core/branding";
import { ProjectResultSchema, ProjectStateSchema, type ProjectResult, type ProjectState } from "../core/project";
import * as services from "./services";
import { fault } from "./errors";
import { generatedPreview, htmlEntry, inspectConfig, inspectEntry } from "./vite";

/** SOURCE OF TRUTH: executeProjectCommand trusted project operations.
 * WHAT: validate RESOURCES inputs, host compatibility, integration identity and recovery state.
 * WHY: CLI and later adapters share policy before any scoped mutation.
 * WHERE: core/project owns public contracts; vite owns pure source adaptation; services owns effects.
 */
const PackageSchema = z.object({
  name: z.string().optional(), version: z.string().optional(), packageManager: z.string().optional(),
  workspaces: z.unknown().optional(),
  dependencies: z.record(z.string(), z.string()).optional(),
  devDependencies: z.record(z.string(), z.string()).optional(),
  scripts: z.record(z.string(), z.string()).optional(),
  exports: z.unknown().optional(),
});
const PendingSchema = z.strictObject({ project: ProjectStateSchema, original: z.string() });
const statePath = ".flute/project.json";
const pendingPath = ".flute/pending.json";
/** SOURCE OF TRUTH: agentHandoff, init-project generated agent entry.
 * WHAT: a discoverable pointer and prompt derived from the canonical installed authoring guide.
 * WHY: agents read current policy through RESOURCES without duplicated guidance or config edits.
 * WHERE: initialize journals the FLUTE.md write through services; CLI presents returned metadata.
 */
function agentHandoff(adapter?: ProjectState["adapter"]) {
  const vue = adapter === "vue" || adapter === "nuxt";
  const guide = RESOURCES["authoring-guide"]();
  const handoff = {
    path: "FLUTE.md" as const,
    guideCommand: "npx flute guide --json" as const,
    guideVersion: guide.version,
    prompt: "Read FLUTE.md and run npx flute guide --json in this project. Create a Flute scene using the existing UI from this host page: <page route or component path>. Follow the installed guide, then show the scene in this app's running preview.",
  };
  const text = `<!-- flute:agent-handoff:v1 -->
# ${FLUTE_BRAND.title}

${FLUTE_BRAND.url}

Generated by Flute init. Authoring guide format: ${handoff.guideVersion}.

From this project root, run \`${handoff.guideCommand}\` and read the returned workflow and capabilities.api before authoring. That command reads this installed version's canonical guide; it owns the scene instructions and examples.

${vue
    ? "Use the installed `@webprodigies/flute/vue` and `@webprodigies/flute/vue/preview` exports and their TypeScript declarations for the exact API. This is a " + (adapter === "nuxt" ? "Nuxt 3/4 project: the studio is the development-only `/flute` page Flute generated (production answers 404); import app components in scenes through the `~/` alias or explicit relative paths. Scene bindings" : "Vue 3 project: scene bindings") + " are `.vue` single-file components that use `<Surface>` slots. This app's recipe directory is `src/flute/scenes`" + (adapter === "nuxt" ? " at the project root" : "") + " (`<id>.scene.json` plus `<id>.vue`); read capabilities.api.vue and capabilities.api.recipes in the guide for the file contract."
    : "Use the installed `@webprodigies/flute` and `@webprodigies/flute/preview` exports and their TypeScript declarations for the exact API. This app's recipe directory is `src/flute/scenes`; read capabilities.api.recipes in the guide for its file contract."}

Tell your coding agent the desired host page route or component path, together with this file. Run \`npx flute scenes --json\` to inspect the app's catalog and \`npx flute open --url <running-app-origin>\` to open its existing dev server.
`;
  return { handoff, text };
}
const configs = ["vite.config.ts", "vite.config.js", "vite.config.mts", "vite.config.mjs", "vite.config.cts", "vite.config.cjs"];
const locks = ["package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "bun.lock", "bun.lockb"];
function decode<T>(text: string, schema: z.ZodType<T>, target: string): T {
  try { return schema.parse(JSON.parse(text)); }
  catch { throw fault("invalid-file", "Invalid or conflicting project metadata; review " + target + ".", target); }
}
async function packageAt(root: string, target: string) {
  const dependency=/^node_modules\/(react|react-dom|vue|nuxt|@webprodigies\/flute)\/package.json$/.exec(target);
  const source = dependency ? await services.readDependency(root,dependency[1]) : await services.readText(root, target);
  return source === undefined ? undefined : decode(source, PackageSchema, target);
}
async function inspectProject(root: string) {
  // Preflight every mutation/config target, including unused conflicting lock/config candidates.
  for (const target of [statePath, pendingPath, "package.json", ...locks, ...configs])
    await services.scopedPath(root, target);
  const pkg = await packageAt(root, "package.json");
  if (!pkg) throw fault("unsupported-project", "Choose an existing npm Vite React project containing package.json.");
  if (pkg.workspaces !== undefined || (pkg.packageManager && !/^npm@\d/.test(pkg.packageManager)))
    throw fault("unsupported-project", "Automatic setup supports a single-root npm project; adapt this package manager/workspace manually.");
  const existingLocks: string[] = [];
  for (const target of locks) if (await services.readText(root, target) !== undefined) existingLocks.push(target);
  if (existingLocks.some(lock => !["package-lock.json", "npm-shrinkwrap.json"].includes(lock)) || existingLocks.length > 1)
    throw fault("unsupported-project", "Resolve conflicting or non-npm lockfiles before setup.");
  const dependencies = { ...pkg.devDependencies, ...pkg.dependencies };
  if (!dependencies.vite || !dependencies.react
    || !dependencies["react-dom"]
    || !/^vite(?:\s+--host(?:[ =](?:localhost|127\.0\.0\.1|\[::1\]))?)?(?:\s+--port[ =]\d+)?(?:\s+--strictPort)?$/.test(pkg.scripts?.dev ?? ""))
    throw fault("unsupported-project", "Vite entry setup requires a standard Vite dev script. Use flute init --adapter react for a custom renderer without changing its build tool.");
  const found: string[] = [];
  for (const target of configs) {
    const source = await services.readText(root, target);
    if (source !== undefined) { found.push(target); inspectConfig(source, target); }
  }
  if (found.length > 1) throw fault("unsupported-project", "Multiple Vite configuration files are ambiguous.");
  if (!found.length) throw fault("unsupported-project", "Use a static Vite configuration with a standard React plugin for scene refresh.");
  const html = await services.readText(root, "index.html");
  if (html === undefined) throw fault("unsupported-project", "Expected index.html at the project root.");
  const entry = services.relativeTarget(htmlEntry(html));
  const source = await services.readText(root, entry);
  if (source === undefined) throw fault("unsupported-project", "The index.html module entry is missing.", entry);
  return { entry, source, pkg };
}
const isVueFamily = (adapter?: ProjectState["adapter"]) => adapter === "vue" || adapter === "nuxt";
async function hostDependenciesValid(root: string, adapter?: ProjectState["adapter"]) {
  if (isVueFamily(adapter)) {
    const installed = await packageAt(root, "node_modules/vue/package.json");
    if (!installed?.version || !/^3\.(?:[5-9]|[1-9]\d+)\.\d+/.test(installed.version))
      throw fault("missing-installation", "Missing or incompatible installed vue. Run npm install in this project's root to install its declared Vue 3.5+ dependency, then retry npx flute init.", "node_modules/vue/package.json");
    return;
  }
  for (const name of ["react", "react-dom"]) {
    const installed = await packageAt(root, "node_modules/" + name + "/package.json");
    if (!installed?.version || !/^(?:18\.(?:[2-9]|[1-9]\d+)\.\d+|19\.\d+\.\d+)$/.test(installed.version))
      throw fault("missing-installation", `Missing or incompatible installed ${name}. Run npm install in this project's root to install its declared React 18.2+ or 19.x dependencies, then retry npx flute init.`, "node_modules/" + name + "/package.json");
  }
}
async function installationValid(root: string, requireToolkit = true, adapter?: ProjectState["adapter"]) {
  const pkg = await packageAt(root, "package.json");
  await hostDependenciesValid(root, adapter);
  const toolkit = await packageAt(root, "node_modules/@webprodigies/flute/package.json");
  if (!toolkit) {
    if (requireToolkit) throw fault("missing-installation", "Flute is not installed. Install your local Flute .tgz with npm install /path/to/flute.tgz, then run npx flute init.");
    return false;
  }
  if (toolkit.name !== "@webprodigies/flute" || !(pkg?.dependencies?.["@webprodigies/flute"] || pkg?.devDependencies?.["@webprodigies/flute"]))
    throw fault("conflict", "Flute installation must match a declared @webprodigies/flute dependency.");
  const exports = toolkit.exports;
  const entry = isVueFamily(adapter) ? "./vue/preview" : "./preview";
  const preview = exports && typeof exports === "object" && !Array.isArray(exports) ? (exports as Record<string, unknown>)[entry] : undefined;
  const target = typeof preview === "string" ? preview
    : preview && typeof preview === "object" && !Array.isArray(preview) ? (preview as Record<string, unknown>).import : undefined;
  if (typeof target !== "string" || !target.startsWith("./")
    || await services.readDependency(root, "@webprodigies/flute", target.slice(2)) === undefined)
    throw fault("missing-installation", "Installed @webprodigies/flute lacks the preview entry. Install the supported Flute package and retry.");
  return true;
}
async function sourceForInstall(root: string, source: string | undefined) {
  if (!source) throw fault("package-unavailable", "Install Flute in this app with npm install @webprodigies/flute, then run npx flute init. For a local source build, supply --package with its .tgz file.");
  if (!source.endsWith(".tgz") || source.startsWith("-") || source.includes("://"))
    throw fault("invalid-input", "Package source must be an explicit local .tgz file.");
  return services.localPackageSource(root, source);
}
async function stateFor(root: string) {
  const text = await services.readText(root, statePath);
  return { text, project: text === undefined ? undefined : decode(text, ProjectStateSchema, statePath) };
}
function checkState(project: ProjectState, entry: string) {
  services.relativeTarget(project.entry);
  if (project.entry !== entry) throw fault("conflict", "Recorded Flute entry differs from index.html; review the integration.", statePath);
}
async function previewAdapterFor(root: string, entry: string) {
  const adapter = generatedPreview(entry);
  // Vite resolves these extensions before an extensionless import. Never let an
  // unrelated sibling shadow the generated component, including JSX/TSX switches.
  for (const extension of ["mjs", "js", "mts", "ts", "jsx", "tsx", "json"]) {
    const candidate = adapter.path.replace(/\.[jt]sx$/, "." + extension);
    if (candidate !== adapter.path && await services.readText(root, candidate) !== undefined)
      throw fault("conflict", "A file conflicts with Flute's preview adapter import. Move or rename it before setup.", candidate);
  }
  const existing = await services.readText(root, adapter.path);
  if (existing !== undefined && existing !== adapter.text && existing !== adapter.text.replace("scene.json,tsx,jsx", "scene.json,tsx"))
    throw fault("conflict", "Flute preview adapter already contains different content. Move or rename it, then retry flute init.", adapter.path);
  return { ...adapter, existing };
}
async function initialize(root: string, packageSource: string | undefined, requestedAdapter?: string): Promise<ProjectResult> {
  const portable = await portableHost(root, requestedAdapter);
  if (portable) return initializePortable(root, portable, packageSource);
  const host = await inspectProject(root);
  const adapter = await previewAdapterFor(root, host.entry);
  const adapterText = adapter.existing;
  const generated = agentHandoff();
  const handoffText = await services.readText(root, generated.handoff.path);
  if (handoffText !== undefined && handoffText !== generated.text)
    throw fault("conflict", "FLUTE.md already contains different content. Move or rename it to preserve your document, then retry npx flute init to generate the installed agent handoff.", generated.handoff.path);
  const saved = await stateFor(root);
  const pendingText = await services.readText(root, pendingPath);
  const pending = pendingText === undefined ? undefined : decode(pendingText, PendingSchema, pendingPath);
  if (saved.project) checkState(saved.project, host.entry);
  if (pending) {
    checkState(pending.project, host.entry);
    if (saved.project && saved.project.projectId !== pending.project.projectId)
      throw fault("conflict", "Pending setup belongs to another project identity.", pendingPath);
  }
  const project = saved.project ?? pending?.project ?? ProjectStateSchema.parse({
    version: 1, projectId: services.newProjectId(), entry: host.entry, packageManager: "npm",
  });
  const adapted = inspectEntry(host.source, host.entry, project.projectId);
  if (pending) {
    const planned = inspectEntry(pending.original, host.entry, project.projectId);
    if ((planned.integrated && !saved.project) || (host.source !== pending.original && adapted.text !== planned.text))
      throw fault("conflict", "Entry changed during interrupted setup; restore the pending original or complete integration before retrying.", host.entry);
  } else if (saved.project && !adapted.integrated) {
    throw fault("conflict", "Recorded project no longer contains its Flute integration; review entry changes.", host.entry);
  }
  let installed = false;
  // Host dependency failures must not be disguised as a missing Flute tarball.
  await hostDependenciesValid(root);
  try { installed = await installationValid(root, false); }
  catch (error) {
    if (!packageSource || !(error instanceof Error) || !("code" in error)
      || !["missing-installation", ...(pending ? ["conflict", "invalid-file"] : [])].includes(String(error.code))) throw error;
  }
  const installSource = installed ? undefined : await sourceForInstall(root, packageSource);
  if (saved.project && adapted.integrated && adapted.text === host.source && !pending && installed
    && handoffText === generated.text && adapterText === adapter.text)
    return { success: true, data: { project, changed: false, handoff: generated.handoff } };
  const journal = pendingText ?? JSON.stringify({ project, original: host.source }, null, 2) + "\n";
  if (!pendingText) await services.atomicWrite(root, pendingPath, journal, undefined);
  if (installSource) {
    await services.installPackage(root, installSource);
    await installationValid(root);
  }
  // Recheck host/config after npm, which may have changed files or been interrupted.
  const after = await inspectProject(root);
  if (after.entry !== host.entry || after.source !== host.source)
    throw fault("conflict", "Project entry changed during installation; retry after reviewing it.", host.entry);
  // The journal covers this generated dependency too. Recheck before other generated writes;
  // create-only transport and exact bytes permit retry after an adapter/entry interruption.
  if ((await previewAdapterFor(root, host.entry)).existing !== adapterText)
    throw fault("conflict", "Flute preview adapter changed during setup; review it before retrying.", adapter.path);
  // Write before entry/state, so a handoff conflict cannot commit an incomplete setup.
  // An interruption after this write resumes by recognizing the exact generated bytes.
  if (handoffText === undefined) await services.atomicWrite(root, generated.handoff.path, generated.text, undefined);
  else if (await services.readText(root, generated.handoff.path) !== generated.text)
    throw fault("conflict", "FLUTE.md changed during setup; review it before retrying npx flute init.", generated.handoff.path);
  if (adapterText !== adapter.text) await services.atomicWrite(root, adapter.path, adapter.text, adapterText);
  if (adapted.text !== host.source) await services.atomicWrite(root, host.entry, adapted.text, host.source);
  const state = JSON.stringify(project, null, 2) + "\n";
  if (!saved.project) await services.atomicWrite(root, statePath, state, saved.text);
  await services.removeText(root, pendingPath, journal);
  return { success: true, data: { project, changed: true, handoff: generated.handoff } };
}
async function load(root: string) {
  const portable = await stateFor(root);
  if (portable.project?.adapter) { await verifyPortable(root, portable.project); return portable.project; }
  const host = await inspectProject(root);
  const saved = await stateFor(root);
  if (!saved.project) throw fault("not-initialized", "Run flute init in this project first.");
  checkState(saved.project, host.entry);
  if (await services.readText(root, pendingPath) !== undefined)
    throw fault("incomplete-setup", "Setup was interrupted. Run flute init again to resume safely.");
  const adapted = inspectEntry(host.source, host.entry, saved.project.projectId);
  if (!adapted.integrated)
    throw fault("conflict", "The recorded Flute integration is missing.", host.entry);
  if (adapted.text !== host.source)
    throw fault("incomplete-setup", "Run flute init to upgrade the installed preview refresh boundary.", host.entry);
  const adapter = await previewAdapterFor(root, host.entry);
  if (adapter.existing !== adapter.text)
    throw fault("conflict", "The generated preview adapter is missing or changed. Review it and run flute init.", adapter.path);
  await installationValid(root);
  return saved.project;
}
/** SOURCE OF TRUTH: verifyVueConnection static wrap check.
 * WHAT: find a host source (outside src/flute) that imports the generated ProjectPreview.vue and renders it.
 * WHY: without the wrap, ?flute-preview=1 silently shows the plain app; fail early with the exact snippet.
 * WHERE: services.scanFiles bounds the read; the identifier the file chose is honored, so renamed imports pass.
 */
const generatedImport = /import\s+([A-Za-z_$][\w$]*)\s*(?:,\s*\{[^}]*\}\s*)?from\s*["'][^"']*\bflute\/ProjectPreview\.vue["']/g;
const generatedLazy = /(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*[^;\n]*?import\(\s*["'][^"']*\bflute\/ProjectPreview\.vue["']\s*\)/g;
function usesWrapper(text: string, identifier: string) {
  const code = text.replace(/<!--[\s\S]*?-->/g, "").replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  const kebab = identifier.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
  const names = [identifier, kebab].map(name => name.replace(/[$]/g, "\\$"));
  return new RegExp(`<(?:${names.join("|")})(?=[\\s/>])`).test(code)
    || new RegExp(`\\b(?:h|createVNode|createBlock|createElementBlock|_createVNode|_createBlock)\\(\\s*${names[0]}\\b`).test(code);
}
async function verifyVueConnection(root: string, project: ProjectState) {
  if (project.adapter !== "vue") return;
  const files = await services.scanFiles(root, "src", { extensions: [".vue", ".ts", ".js", ".tsx", ".jsx"], exclude: ["src/flute"] });
  let imported = false;
  for (const file of files) {
    let text: string | undefined;
    try { text = await services.readText(root, file, 512_000); } catch { continue; }
    if (text === undefined) continue;
    for (const pattern of [generatedImport, generatedLazy]) {
      for (const match of text.matchAll(pattern)) {
        imported = true;
        if (usesWrapper(text, match[1])) return;
      }
    }
  }
  throw fault("missing-connection", (imported
    ? "The generated Flute component is imported but never rendered in a template. "
    : "No host source imports the generated Flute component, so ?flute-preview=1 would show the plain app. ") + vueConnectionStep + " Then retry.", vueEntry);
}
async function openPreview(root: string, input: z.output<typeof RESOURCES["open-preview"]>) {
  const project = await load(root);
  if (project.adapter) {
    if (project.adapter === "vue") {
      await verifyVueConnection(root, project);
      // The generated component embeds this project's identity; Vite serves it as a transformed module.
      // Retry within a fixed budget for a starting dev server, and never accept a different project.
      let matched = false;
      for (let attempt = 0; attempt < 5 && !matched; attempt++) {
        try {
          const transformed = await services.fetchText(new URL("/" + vueEntry, input.url).href);
          if (!transformed.includes(project.projectId) || !transformed.includes("ProjectPreview"))
            throw fault("wrong-dev-server", "Dev server does not contain this project's preview identity.");
          matched = true;
        } catch { if (attempt < 4) await services.pause(150); }
      }
      if (!matched) throw fault("missing-dev-server", "No matching Vite dev server at " + input.url + ". Run npm run dev in this project, then retry with its loopback URL. Flute will not start another server or change its port.");
      const url = new URL("/?flute-preview=1", input.url).href;
      if (input.launch) await services.openBrowser(root, url);
      return {success:true as const,data:{project,url}};
    }
    if (project.adapter === "react") throw fault("manual-preview", "Open your React renderer's route with ?flute-preview=1 after mounting src/flute/ProjectPreview.jsx. Electron renderers keep their own navigation and dev server.");
    const url = new URL("/flute?flute-preview=1", input.url).href;
    const html = project.adapter === "nuxt"
      ? await services.fetchText(url, 30_000).catch(() => { throw fault("missing-dev-server", "No Nuxt dev server answered at " + url + ". Run npm run dev in this project (development only), then retry with its loopback URL. Flute will not start another server or change its port."); })
      : await services.fetchText(url, 30_000);
    if (!html.includes('name="flute-project"') || !html.includes(project.projectId))
      throw fault("wrong-dev-server", "This URL does not serve this project's development Flute route. Start the existing app and check its origin.");
    if (input.launch) await services.openBrowser(root, url);
    return {success:true as const,data:{project,url}};
  }
  // Atomic entry edits and npm changes can briefly leave Vite serving its old module.
  // Retry identity checks within a fixed budget; never accept a different project.
  let matched = false;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      const html = await services.fetchText(input.url);
      const entry = services.relativeTarget(htmlEntry(html, true));
      if (entry !== project.entry) throw fault("wrong-dev-server", "The dev server belongs to another entry.");
      const transformed = await services.fetchText(new URL("/" + entry, input.url).href);
      if (!transformed.includes(project.projectId) || !transformed.includes("ProjectPreview")
        || !(transformed.includes("@webprodigies_flute_preview") || transformed.includes("@webprodigies/flute/preview") || transformed.includes("/src/flute/ProjectPreview.")))
        throw fault("wrong-dev-server", "Dev server does not contain this project's preview identity.");
      matched = true;
      break;
    } catch {
      if (attempt < 4) await services.pause(150);
    }
  }
  if (!matched) throw fault("missing-dev-server", "No matching Vite dev server at " + input.url + ". Run npm run dev in this project, then retry with its loopback URL. Flute will not start another server or change its port.");
  const url = new URL("/?flute-preview=1", input.url).href;
  if (input.launch) await services.openBrowser(root, url);
  return { success: true as const, data: { project, url } };
}
export async function executeProjectCommand(operation: unknown, input: unknown, context: { root: string }): Promise<ProjectResult> {
  try {
    if (typeof operation !== "string" || !Object.hasOwn(RESOURCES, operation))
      throw fault("invalid-operation", "Unknown project operation.");
    const schema = RESOURCES[operation as keyof typeof RESOURCES];
    if (!("safeParse" in schema)) throw fault("invalid-operation", "This operation is not a project command.");
    const parsed = schema.safeParse(input);
    if (!parsed.success) return ProjectResultSchema.parse({ success: false, issues: parsed.error.issues.map(issue => ({
      code: "invalid-input", message: issue.message, path: issue.path.join("."),
    })) });
    if (!context || typeof context.root !== "string") throw fault("invalid-scope", "Provide an absolute local project root.");
    const root = await services.canonicalRoot(context.root);
    let result: ProjectResult;
    if (operation === "init-project") result = await initialize(root, (parsed.data as z.output<typeof RESOURCES["init-project"]>).packageSource, (parsed.data as z.output<typeof RESOURCES["init-project"]>).adapter);
    else if (operation === "sync-project") result = await synchronize(root);
    else if (operation === "open-preview") result = await openPreview(root, parsed.data as z.output<typeof RESOURCES["open-preview"]>);
    else if (operation === "validate-project") {
      const project = await load(root);
      await verifyVueConnection(root, project);
      result = { success: true, data: { project } };
    } else result = { success: true, data: { project: await load(root) } };
    return ProjectResultSchema.parse(result);
  } catch (error) {
    const known = error instanceof Error && "code" in error && "target" in error;
    return { success: false, issues: [{
      code: known ? String(error.code) : "project-error",
      message: known ? error.message : "Unable to access the project. Check local files and permissions, then retry.",
      ...(known && typeof error.target === "string" ? { path: error.target } : {}),
    }] };
  }
}


// SOURCE OF TRUTH: portable project setup and sync.
// WHAT: additive framework connections with a journal and exact owned-file comparisons.
// WHY: unknown React hosts keep their entry/config; known routing adapters only add a studio route.
// WHERE: portable.ts generates imports; discovery.ts validates the same catalog as the CLI.
const ManagedSchema = z.strictObject({project:ProjectStateSchema,files:z.record(z.string(),z.string())});
const managedPath = ".flute/integration.json";
const portablePendingPath = ".flute/integration-pending.json";
type PortableHost = {adapter:"react"|"vue"|"nuxt"|"next-app"|"next-pages";entry:string};
const vueEntry = "src/flute/ProjectPreview.vue";
/** SOURCE OF TRUTH: the one Vue host step. init prints it; open/validate repeat it when the wrap is missing. */
const vueConnectionStep = "One host step remains: in App.vue, import FluteProjectPreview from './flute/ProjectPreview.vue' and wrap the root content, for example <FluteProjectPreview :enabled=\"import.meta.env.DEV\"><RouterView /></FluteProjectPreview> (assign import.meta.env.DEV to a const in <script setup>).";
const nuxtConfigs = ["nuxt.config.ts","nuxt.config.js","nuxt.config.mjs","nuxt.config.mts","nuxt.config.cjs","nuxt.config.cts"];
const nuxtPagePattern = /^(?:[A-Za-z0-9_.-]+\/)*pages\/flute\.vue$/;
const majorOf = (version: string | undefined) => { const match = /(\d+)(?:\.|$|\s)/.exec((version ?? "").replace(/^(?:npm:[^@]+@)?[\^~<>=v\s]*/, "")); return match ? Number(match[1]) : undefined; };
/** SOURCE OF TRUTH: nuxtEntry, the Nuxt pages directory and studio route location.
 * WHAT: refuse Nuxt 2, find <srcDir>/pages (srcDir from a static nuxt.config, else app/ when it exists, else the root)
 * and return <pages>/flute.vue. A dynamic or unparseable config falls back to the directories that exist.
 * WHY: a page is the only additive connection, and adding one to an app with no pages directory would switch on
 * vue-router and change how the app renders, so that case fails with instructions instead of guessing.
 * WHERE: portableHost calls it during init only; the chosen entry is then recorded in .flute/project.json.
 */
async function nuxtEntry(root:string, declared:string):Promise<string> {
  const declaredMajor = majorOf(declared);
  const installedMajor = majorOf((await packageAt(root,"node_modules/nuxt/package.json"))?.version);
  if ((declaredMajor !== undefined && declaredMajor < 3) || (installedMajor !== undefined && installedMajor < 3))
    throw fault("unsupported-project","Nuxt 2 is not supported. Flute supports Nuxt 3 and Nuxt 4 (Vue 3.5+); upgrade Nuxt, or use a Vue 3 + Vite app.");
  let config = "";
  for (const name of nuxtConfigs) {
    const text = await services.readText(root,name,256_000);
    if (text !== undefined) { config = text.replace(/\/\*[\s\S]*?\*\//g,"").replace(/^\s*\/\/.*$/gm,""); break; }
  }
  const staticDir = /\bsrcDir\s*:\s*(["'])([^"'$`\\]+)\1/.exec(config)?.[2]?.replace(/^\.\//,"").replace(/\/+$/,"");
  const dynamicDir = /\bsrcDir\s*:/.test(config) && staticDir === undefined;
  let srcDir = staticDir === undefined ? "" : staticDir === "." ? "" : staticDir;
  if (staticDir === undefined) srcDir = (await services.scanDirectory(root,"app",1024)).length ? "app" : "";
  const prefix = srcDir ? srcDir + "/" : "";
  const pagesDir = prefix + "pages";
  const routerOff = /\bpages\s*:\s*false\b/.test(config);
  const routerOn = /\bpages\s*:\s*true\b/.test(config);
  if (routerOff || (!routerOn && !(await services.scanDirectory(root,pagesDir,1024)).length))
    throw fault("unsupported-project",`This Nuxt app has no ${pagesDir}/ directory${routerOff ? " (pages: false)" : ""}, so vue-router is off and a /flute page would switch it on and change how your app renders. Flute will not do that. Add ${pagesDir}/index.vue with your existing page content (and <NuxtPage /> in app.vue) first, then retry npx flute init${dynamicDir ? "; note that nuxt.config sets srcDir dynamically, so Flute looked in " + pagesDir + "/" : ""}.`);
  const entry = pagesDir + "/flute.vue";
  if (!nuxtPagePattern.test(entry)) throw fault("unsupported-project","Nuxt srcDir must be a plain project-relative directory.");
  services.relativeTarget(entry);
  return entry;
}
async function portableHost(root:string, requested?:string):Promise<PortableHost|undefined> {
  const pkg = await packageAt(root,"package.json");
  if (!pkg) throw fault("unsupported-project","Run flute init in your existing React or Vue application's package directory.");
  const deps = {...pkg.devDependencies,...pkg.dependencies};
  const saved = await stateFor(root);
  // A Nuxt 3/4 host is detected by its nuxt dependency; --adapter nuxt selects it explicitly.
  if (deps.nuxt !== undefined || requested === "nuxt" || saved.project?.adapter === "nuxt") {
    if (requested === "react" || requested === "vue") throw fault("unsupported-project",`This is a Nuxt app; run flute init without --adapter (or with --adapter nuxt) instead of --adapter ${requested}.`);
    if (saved.project?.adapter && saved.project.adapter !== "nuxt") throw fault("conflict","Existing Flute setup uses another host connection.");
    if (deps.nuxt === undefined) throw fault("unsupported-project","Nuxt setup needs a nuxt dependency in package.json. Run flute init in your Nuxt application's package directory.");
    return {adapter:"nuxt",entry:saved.project?.entry ?? await nuxtEntry(root,deps.nuxt)};
  }
  // A Vue + Vite host (no react-dom) is detected automatically; --adapter vue selects it explicitly.
  const vue = saved.project?.adapter === "vue" || requested === "vue"
    || (requested !== "react" && !saved.project?.adapter && !!deps.vue && !deps["react-dom"]);
  if (vue) {
    if (saved.project?.adapter && saved.project.adapter !== "vue") throw fault("conflict","Existing Flute setup uses another host connection.");
    if (!deps.vue || !deps.vite || !deps["@vitejs/plugin-vue"])
      throw fault("unsupported-project","Vue setup needs vue, vite and @vitejs/plugin-vue in package.json. Run flute init in your Vue + Vite application's package directory.");
    return {adapter:"vue",entry:vueEntry};
  }
  if (!deps.react || !deps["react-dom"]) throw fault("unsupported-project","This package needs a React DOM renderer or a Vue 3 + Vite app. Run setup in the web/renderer package containing React and react-dom, or vue and @vitejs/plugin-vue.");
  if (saved.project?.adapter) return {adapter:saved.project.adapter as PortableHost["adapter"],entry:saved.project.entry};
  if (requested === "react") return {adapter:"react",entry:"src/flute/ProjectPreview.jsx"};
  if (deps.next) {
    for (const base of ["app","src/app"]) {
      for (const extension of ["tsx","jsx","js"]) {
        if (await services.isRegularFile(root,base+"/layout."+extension))
          return {adapter:"next-app",entry:base+"/flute/page.jsx"};
      }
    }
    for (const base of ["pages","src/pages"]) {
      if ((await services.scanDirectory(root,base,1024)).length)
        return {adapter:"next-pages",entry:base+"/flute.jsx"};
    }
    // Unusual Next routing remains usable via the same manual React adapter.
    return {adapter:"react",entry:"src/flute/ProjectPreview.jsx"};
  }
  if (deps.vite) {
    if (!saved.project && await services.readText(root,pendingPath) === undefined) {
      try {
        const host=await inspectProject(root);
        inspectEntry(host.source,host.entry,"00000000-0000-4000-8000-000000000000");
      } catch(error) {
        if (!(error instanceof Error) || !("code" in error) || error.code!=="unsupported-project") throw error;
        return {adapter:"react",entry:"src/flute/ProjectPreview.jsx"};
      }
    }
    return undefined;
  }
  return {adapter:"react",entry:"src/flute/ProjectPreview.jsx"};
}
function integrationInfo(project:ProjectState) {
  if (project.adapter === "vue") return {
    kind:"vue",component:vueEntry,
    instructions:vueConnectionStep+" Scene pairs are <id>.scene.json + <id>.vue in src/flute/scenes; Vite's glob discovers them, and npx flute sync validates them. Open the app with ?flute-preview=1.",
  };
  if (project.adapter === "nuxt") return {
    kind:"nuxt",component:project.entry,route:"/flute",
    instructions:"Start the existing Nuxt dev server and open /flute (development only; production answers 404). Your app.vue, layouts and pages stay intact and the app is not wrapped. Scene pairs are <id>.scene.json + <id>.vue in src/flute/scenes at the project root; the page's Vite glob discovers them, and npx flute sync validates them. Import Surface from '@webprodigies/flute/vue' and reach app components with the ~ alias.",
  };
  return {
    kind:project.adapter!,component:"src/flute/ProjectPreview.jsx",
    ...(project.adapter === "react" ? {} : {route:"/flute"}),
    instructions:project.adapter === "react"
      ? "One host connection remains: import { FluteProjectPreview } from src/flute/ProjectPreview.jsx and wrap the existing UI inside its providers with enabled={yourDevelopmentFlag}. Open that renderer with ?flute-preview=1. Do not change its bundler, router or Electron main/preload. After adding/removing scene files run npx flute sync."
      : "Start the existing Next.js app and open /flute (development only). Existing layouts/providers stay intact. After adding/removing scene files run npx flute sync; metadata and component edits use the host's hot reload.",
  };
}
async function validScenes(root:string) {
  const catalog = await discoverRecipes(root);
  if (catalog.issues.length) throw fault("invalid-scenes",catalog.issues.map(issue=>issue.path+": "+issue.message).join("\n"));
  return catalog;
}
async function catalogSource(root:string) {
  return portableCatalog((await validScenes(root)).scenes);
}
async function portableFiles(root:string, project:ProjectState, catalog:string) {
  const allowed=project.adapter==="next-app" ? ["app/flute/page.jsx","src/app/flute/page.jsx"]
    : project.adapter==="next-pages" ? ["pages/flute.jsx","src/pages/flute.jsx"] : project.adapter==="vue" ? [vueEntry] : project.adapter==="nuxt" ? undefined : ["src/flute/ProjectPreview.jsx"];
  if(allowed ? !allowed.includes(project.entry) : !nuxtPagePattern.test(project.entry))throw fault("conflict","Recorded entry is not a valid host connection.");
  const files = portableIntegration(project,catalog);
  // Alternative source extensions must not shadow our generated route/component.
  for (const target of Object.keys(files)) {
    await services.scopedPath(root,target);
    if (/\.jsx$/.test(target)) for (const extension of ["js","tsx","ts","mjs"]) {
      const other=target.replace(/\.jsx$/,"."+extension);
      if (await services.isRegularFile(root,other)) throw fault("conflict","An existing file owns this route or component; use --adapter react to choose a manual connection instead.",other);
    }
  }
  if(project.adapter === "nuxt") {
    // Another page file or a directory route for the same path would shadow or collide with the generated page.
    const base=project.entry.replace(/\.vue$/,"");
    for(const other of ["ts","js","tsx","jsx","md"].map(extension=>base+"."+extension).concat(["vue","ts","js","tsx","jsx"].map(extension=>base+"/index."+extension)))
      if(await services.isRegularFile(root,other))throw fault("conflict","An existing page owns the /flute route. Rename it or remove it before running flute init.",other);
  }
  if(project.adapter === "next-app") for(const extension of ["ts","js"]) {
    const other=project.entry.replace(/page.jsx$/,"route."+extension);
    if(await services.isRegularFile(root,other))throw fault("conflict","An existing route handler owns /flute. Use --adapter react.",other);
  }
  return files;
}
async function initializePortable(root:string, host:PortableHost, packageSource?:string):Promise<ProjectResult> {
  const saved=await stateFor(root);
  const pendingText=await services.readText(root,portablePendingPath);
  const pending=pendingText===undefined?undefined:decode(pendingText,ManagedSchema,portablePendingPath);
  const existingText=await services.readText(root,managedPath);
  const existing=existingText===undefined?undefined:decode(existingText,ManagedSchema,managedPath);
  const project=saved.project??pending?.project??ProjectStateSchema.parse({version:1,projectId:services.newProjectId(),entry:host.entry,packageManager:"npm",adapter:host.adapter});
  if(project.adapter!==host.adapter||project.entry!==host.entry)throw fault("conflict","Existing Flute setup uses another host connection.");
  for(const record of [pending,existing])if(record && JSON.stringify(record.project)!==JSON.stringify(project))throw fault("conflict","Flute setup identity changed; inspect .flute before retrying.");
  // Vue and Nuxt hosts use Vite's glob, so there is no generated catalog to journal or validate at setup time.
  const catalog=isVueFamily(host.adapter) ? "" : existing?.files["src/flute/catalog.js"]??pending?.files["src/flute/catalog.js"]??await catalogSource(root);
  const files=await portableFiles(root,project,catalog);
  const generated=agentHandoff(project.adapter);
  files[generated.handoff.path]=generated.text;
  if(pending && JSON.stringify(pending.files)!==JSON.stringify(files))throw fault("conflict","Pending setup differs from the generated connection; review it before retrying.");
  if(existing && JSON.stringify(existing.files)!==JSON.stringify(files))throw fault("conflict","Managed Flute files differ from this installed adapter.");
  // Finish all conflict/dependency checks before any writes.
  for(const [target,text] of Object.entries(files)) {
    const current=await services.readText(root,target);
    if(current!==undefined && current!==text)throw fault("conflict","Flute will not overwrite an existing or edited file. Preserve it before retrying.",target);
  }
  await hostDependenciesValid(root,project.adapter);
  const installed=await installationValid(root,false,project.adapter);
  const source=installed?undefined:await sourceForInstall(root,packageSource);
  if(existing && saved.project && !pending) {
    await verifyPortable(root,project);
    return {success:true,data:{project,changed:false,handoff:generated.handoff,integration:integrationInfo(project)}};
  }
  const journal=JSON.stringify({project,files},null,2)+"\n";
  if(!pendingText)await services.atomicWrite(root,portablePendingPath,journal,undefined);
  if(source){await services.installPackage(root,source);await installationValid(root,true,project.adapter);}
  for(const [target,text] of Object.entries(files)) {
    const current=await services.readText(root,target);
    if(current===undefined)await services.atomicWrite(root,target,text,undefined);
    else if(current!==text)throw fault("conflict","File changed during setup.",target);
  }
  if(!existing)await services.atomicWrite(root,managedPath,journal,undefined);
  if(!saved.project)await services.atomicWrite(root,statePath,JSON.stringify(project,null,2)+"\n",saved.text);
  await services.removeText(root,portablePendingPath,pendingText??journal);
  return {success:true,data:{project,changed:true,handoff:generated.handoff,integration:integrationInfo(project)}};
}
async function verifyPortable(root:string,project:ProjectState) {
  if(await services.readText(root,portablePendingPath)!==undefined)throw fault("incomplete-setup","Run flute init to resume interrupted setup.");
  const text=await services.readText(root,managedPath);
  if(text===undefined)throw fault("incomplete-setup","Missing managed connection. Run flute init.");
  const managed=decode(text,ManagedSchema,managedPath);
  if(JSON.stringify(managed.project)!==JSON.stringify(project))throw fault("conflict","Managed project identity differs.");
  const expected=await portableFiles(root,project,managed.files["src/flute/catalog.js"]??"");
  expected["FLUTE.md"]=agentHandoff(project.adapter).text;
  if(JSON.stringify(expected)!==JSON.stringify(managed.files))throw fault("conflict","Managed file list differs from the canonical connection.");
  for(const [target,content] of Object.entries(expected))if(await services.readText(root,target)!==content)throw fault("conflict","Generated connection changed or is missing. Keep customizations in your scene components.",target);
  await installationValid(root,true,project.adapter);
}
async function synchronize(root:string):Promise<ProjectResult> {
  const project=(await stateFor(root)).project;
  if(!project)throw fault("not-initialized","Run flute init first.");
  if(!project.adapter){await load(root);return {success:true,data:{project,changed:false}};}
  if(isVueFamily(project.adapter)) {
    // The Vite glob picks scene files up on its own: validate the same catalog, never write one.
    await verifyPortable(root,project);
    await validScenes(root);
    return {success:true,data:{project,changed:false}};
  }
  const transactionPath=".flute/catalog-pending.json";
  const interrupted=await services.readText(root,transactionPath);
  if(interrupted!==undefined) {
    const pending=decode(interrupted,z.strictObject({before:z.string(),after:z.string()}),transactionPath);
    const recordText=await services.readText(root,managedPath);
    if(recordText===undefined)throw fault("conflict","Missing catalog ownership record.");
    const record=decode(recordText,ManagedSchema,managedPath);
    const current=await services.readText(root,"src/flute/catalog.js");
    if(![pending.before,pending.after].includes(record.files["src/flute/catalog.js"]) || ![pending.before,pending.after].includes(current??""))
      throw fault("conflict","Catalog changed during interrupted sync.");
    if(current!==pending.after)await services.atomicWrite(root,"src/flute/catalog.js",pending.after,current);
    if(record.files["src/flute/catalog.js"]!==pending.after) {
      record.files["src/flute/catalog.js"]=pending.after;
      await services.atomicWrite(root,managedPath,JSON.stringify(record,null,2)+"\n",recordText);
    }
    await services.removeText(root,transactionPath,interrupted);
  }
  await verifyPortable(root,project);
  const target="src/flute/catalog.js";
  const text=await catalogSource(root);
  const savedText=(await services.readText(root,managedPath))!;
  const managed=decode(savedText,ManagedSchema,managedPath);
  const original=managed.files[target];
  if(text===original)return {success:true,data:{project,changed:false}};
  // Journal registry replacement so a crash between registry/ownership writes is recoverable.
  const transaction=JSON.stringify({before:original,after:text});
  const pending=await services.readText(root,transactionPath);
  if(pending!==undefined&&pending!==transaction)throw fault("conflict","A catalog sync is pending. Restore the previous file set before retrying.");
  if(pending===undefined)await services.atomicWrite(root,transactionPath,transaction,undefined);
  await services.atomicWrite(root,target,text,original);
  managed.files[target]=text;
  await services.atomicWrite(root,managedPath,JSON.stringify(managed,null,2)+"\n",savedText);
  await services.removeText(root,transactionPath,transaction);
  return {success:true,data:{project,changed:true}};
}
