import type { ProjectState } from "../core/project";

/** SOURCE OF TRUTH: portableIntegration, portableCatalog, framework connection source.
 * WHAT: generate additive host files around the same public ProjectPreview contract.
 * WHY: rendering/catalog policy belongs to React/core; build tools only connect imports and routes.
 * WHERE: project commands validate and write these files; arbitrary React hosts supply their own dev flag.
 */
export function portableIntegration(project: ProjectState, catalog: string): Record<string,string> {
  if (project.adapter === "vue") return { "src/flute/ProjectPreview.vue": vuePreview(project) };
  if (project.adapter === "nuxt") return { [project.entry]: nuxtPage(project) };
  const files: Record<string,string> = {
    "src/flute/catalog.js": catalog,
    "src/flute/ProjectPreview.jsx": `"use client";
import React from "react";
import { ProjectPreview } from "@webprodigies/flute/preview";
import { sceneModules } from "./catalog";
// Host-owned development flag: no process, Vite or Electron globals in this adapter.
export function FluteProjectPreview({ children, enabled, active, ...props }) {
  if (!enabled) return children;
  return <ProjectPreview {...props} projectId=${JSON.stringify(project.projectId)} enabled={enabled} active={active} sceneModules={sceneModules}>{children}</ProjectPreview>;
}
`,
  };
  if (project.adapter === "react") return files;
  files["src/flute/Studio.jsx"] = `"use client";
import React from "react";
import dynamic from "next/dynamic";
const Preview = process.env.NODE_ENV === "development" ? dynamic(() => import("./ProjectPreview").then(m => m.FluteProjectPreview), { ssr: false }) : () => null;
export default function FluteStudio() {
  return <Preview enabled={process.env.NODE_ENV === "development"} active />;
}
`;
  // Relative route imports work with or without a src directory and without aliases.
  const depth = project.entry.split("/").length - 1;
  const studio = "../".repeat(depth) + "src/flute/Studio";
  if (project.adapter === "next-app") {
    files[project.entry] = `import React from "react";
import { notFound } from "next/navigation";
import FluteStudio from ${JSON.stringify(studio)};
export default function FlutePage() {
  if (process.env.NODE_ENV !== "development") notFound();
  return <><meta name="flute-project" content=${JSON.stringify(project.projectId)} /><FluteStudio /></>;
}
`;
  } else {
    files[project.entry] = `import React from "react";
import FluteStudio from ${JSON.stringify(studio)};
export function getServerSideProps() {
  return process.env.NODE_ENV === "development" ? { props: {} } : { notFound: true };
}
export default function FlutePage() {
  return <><meta name="flute-project" content=${JSON.stringify(project.projectId)} /><FluteStudio /></>;
}
`;
  }
  return files;
}

/** SOURCE OF TRUTH: vuePreview generated Vue single-file component.
 * WHAT: a host-owned SFC that owns the DEV-only scene glob and forwards props to the Vue ProjectPreview.
 * WHY: the host already compiles .vue files, so the CLI never rewrites main.ts; Vite's glob discovers scene pairs.
 * WHERE: portableIntegration journals it create-only; the project identity is baked into the module so
 * `flute open` can verify the running dev server serves this project. Runtime props only, no TypeScript syntax.
 */
export function vuePreview(project: ProjectState): string {
  return `<!-- Generated by flute init. Scene imports belong in this component; production renders the slot only. -->
<script setup>
import { ProjectPreview } from "@webprodigies/flute/vue/preview";

const props = defineProps({
  enabled: { type: Boolean, required: true },
  active: { type: Boolean, default: undefined },
  projectId: { type: String, default: undefined },
});
const dev = import.meta.env.DEV;
const sceneModules = dev ? import.meta.glob("/src/flute/scenes/*.{scene.json,vue}") : undefined;
const hot = dev ? import.meta.hot : undefined;
const id = props.projectId ?? ${JSON.stringify(project.projectId)};
</script>

<template>
  <slot v-if="!dev" />
  <ProjectPreview v-else :project-id="id" :enabled="enabled" :active="active" :scene-modules="sceneModules" :hot="hot">
    <slot />
  </ProjectPreview>
</template>
`;
}

/** SOURCE OF TRUTH: nuxtPage generated Nuxt studio route.
 * WHAT: <pages>/flute.vue, a development-only page that renders the Vue scene library and nothing else.
 * WHY: like the Next.js routes, the studio shows the scene library (scene bindings are standalone components), so
 * the app root, router and config stay untouched. Production answers 404 and never bundles the studio: the library
 * and the scene glob sit behind import.meta.dev. The glob is relative to this file because Nuxt resolves an absolute
 * "/src/..." glob against srcDir (app/ in Nuxt 4), and its keys are rewritten to the project-relative
 * src/flute/scenes/... paths the library and recipe policy use. The meta tag lets `flute open` verify server HTML.
 * WHERE: portableIntegration journals it create-only; the entry depth fixes the relative glob prefix.
 */
export function nuxtPage(project: ProjectState): string {
  const scenes = "../".repeat(project.entry.split("/").length - 1) + "src/flute/scenes/*.{scene.json,vue}";
  return `<!-- Generated by flute init. Development-only studio route: production answers 404 and bundles no scenes. -->
<script setup>
import { defineAsyncComponent } from "vue";
import { createError, definePageMeta, useHead } from "#imports";

definePageMeta({ layout: false });
if (!import.meta.dev) throw createError({ statusCode: 404, statusMessage: "Not Found", fatal: true });
useHead({ meta: [{ name: "flute-project", content: ${JSON.stringify(project.projectId)} }] });

const found = import.meta.dev ? import.meta.glob(${JSON.stringify(scenes)}) : {};
const sceneModules = Object.fromEntries(Object.entries(found).map(([path, load]) => [path.replace(/^(?:\\.\\.\\/)+/, ""), load]));
const hot = import.meta.dev ? import.meta.hot : undefined;
const Studio = import.meta.dev
  ? defineAsyncComponent(() => import("@webprodigies/flute/vue/preview").then(module => module.ProjectPreview))
  : undefined;
</script>

<template>
  <ClientOnly>
    <component :is="Studio" v-if="Studio" project-id=${JSON.stringify(project.projectId)} enabled active :scene-modules="sceneModules" :hot="hot" />
  </ClientOnly>
</template>
`;
}

/** SOURCE OF TRUTH: portableCatalog.
 * WHAT: static module references for bundlers without import.meta.glob.
 * WHY: the bundler owns hot reload; the shared SceneModuleLibrary owns loading and validation.
 * WHERE: sync-project supplies validated recipe/binding paths. Metadata edits hot reload normally;
 * adding/removing file pairs requires flute sync. No arbitrary host modules are executed by the CLI.
 */
// Vite resolves extensionless imports for JS/TS/JSX only; a .vue binding keeps its extension.
export function portableCatalog(entries: {source:string;binding:string}[]): string {
  const imports = entries.map((entry,index) => `import recipe${index} from ${JSON.stringify("./scenes/" + entry.source.split("/").pop())};`);
  const mappings = entries.flatMap((entry,index) => [
    `  ${JSON.stringify(entry.source)}: async () => ({default:recipe${index}}),`,
    `  ${JSON.stringify(entry.binding)}: () => import(${JSON.stringify("./scenes/" + entry.binding.split("/").pop()?.replace(/\.[jt]sx$/, ""))}),`,
  ]);
  return '// Generated by flute sync. Edit recipes and components, not this registry.\n' +
    imports.join("\n") + "\nexport const sceneModules = {\n" + mappings.join("\n") + "\n};\n";
}
