<!-- Generated by flute init. Development-only studio route: production answers 404 and bundles no scenes. -->
<script setup>
import { defineAsyncComponent } from "vue";
import { createError, definePageMeta, useHead } from "#imports";

definePageMeta({ layout: false });
if (!import.meta.dev) throw createError({ statusCode: 404, statusMessage: "Not Found", fatal: true });
useHead({ meta: [{ name: "flute-project", content: "7602353b-a971-4518-876b-c0d380e49aa2" }] });

const found = import.meta.dev ? import.meta.glob("../../src/flute/scenes/*.{scene.json,vue}") : {};
const sceneModules = Object.fromEntries(Object.entries(found).map(([path, load]) => [path.replace(/^(?:\.\.\/)+/, ""), load]));
const hot = import.meta.dev ? import.meta.hot : undefined;
const Studio = import.meta.dev
  ? defineAsyncComponent(() => import("@webprodigies/flute/vue/preview").then(module => module.ProjectPreview))
  : undefined;
</script>

<template>
  <ClientOnly>
    <component :is="Studio" v-if="Studio" project-id="7602353b-a971-4518-876b-c0d380e49aa2" enabled active :scene-modules="sceneModules" :hot="hot" />
  </ClientOnly>
</template>
