<!-- Generated by flute init. Scene imports belong in this component; production renders the slot only. -->
<script setup>
import { ProjectPreview } from "@webprodigies/flute/vue/preview";

const props = defineProps({
  enabled: { type: Boolean, required: true },
  active: { type: Boolean, default: undefined },
  projectId: { type: String, default: undefined },
});
const dev = import.meta.env.DEV;
const sceneModules = dev ? import.meta.glob("/src/flute/scenes/*.{scene.json,vue}") : undefined;
const hot = dev ? import.meta.hot : undefined;
const id = props.projectId ?? "b1b72849-4033-4775-913c-97657b80fe6c";
</script>

<template>
  <slot v-if="!dev" />
  <ProjectPreview v-else :project-id="id" :enabled="enabled" :active="active" :scene-modules="sceneModules" :hot="hot">
    <slot />
  </ProjectPreview>
</template>
